### <font color=blue>Javier Antonio García Perdomo </font>
### <font color=red>21004161</font>
### Maestría en Data Science
### <font color=green>Ciencia de Datos en Python V </font>
### <font color=red>29/03/2021</font>

### <h1><center><font color=green>Hoja de trabajo 5 - (Numpy, Pandas, Vectorización)</font>  

### Numpy

### Ejercicio 1 - Crear un conjunto de datos lineal
* Crear un conjunto de datos simple que consta de una sola característica y una etiqueta de la siguiente manera:
1. Asigne una secuencia de números enteros del 6 al 20 (incluyendo 20) a un arreglo de NumPy llamado caracteristica.
2. Asigne 15 valores a un arreglo de NumPy llamado etiqueta de manera que:
    etiqueta = (3) (caracteristica) + 4

In [7]:
import numpy as np

caracteristica=np.arange(6,21,1)
etiqueta=[]
for i in caracteristica:
    et=3*i + 4
    etiqueta.append(et)
etiqueta=np.array(etiqueta)
print(caracteristica)
print(etiqueta)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


### Ejercicio 2 - agregar ruido al conjunto de datos
* Inserte un ruido aleatorio en cada elemento de la matriz etiqueta que ya creó. Para ser más precisos, modifique cada valor asignado a etiqueta agregando un valor "floating-point" aleatorio diferente entre -2 y +2.
No utilice broadcasting. En su lugar, cree un arreglo de ruido que tenga la misma dimensión que etiqueta.


In [9]:
ruido=np.random.uniform(low=-2.0, high=2.0, size=(len(etiqueta),))
print(ruido)

[ 0.6604373   1.5984567   1.81807683  1.5710748  -0.77695908  0.24644875
 -1.40373086  1.81587619 -1.84280384 -0.91918071  0.86930833  1.37384845
  1.25466314 -1.04875416 -0.84100537]


In [10]:
etiquetaruido=etiqueta+ruido
print(etiquetaruido)

[22.6604373  26.5984567  29.81807683 32.5710748  33.22304092 37.24644875
 38.59626914 44.81587619 44.15719616 48.08081929 52.86930833 56.37384845
 59.25466314 59.95124584 63.15899463]


### Pandas

### Ejercicio 3 - Crear un DataFrame
* Hacer lo siguiente:
1. Cree un pandas DataFrame de 10x3 (10 filas x 3 columnas) en el que las columnas se denominen "Data Warehouse", "Python in Data Science", y "Estadistica Aplicada". Llene cada una de las 30 celdas del DataFrame con un número entero aleatorio entre 0 y 100, incluyendo 100.

In [19]:
import pandas as pd
import random
data={"Data Warehouse": random.sample(range(0, 101), 10),
      "Python in Data Science" :random.sample(range(0, 101), 10),
      "Estadistica Aplicada": random.sample(range(0, 101), 10)}
df=pd.DataFrame(data)

2. Despliege lo siguiente:
- Todo el DataFrame

In [20]:
print(df)

   Data Warehouse  Python in Data Science  Estadistica Aplicada
0              93                      81                    96
1              89                      64                    39
2              87                      97                    12
3              84                      26                    40
4              41                      56                    31
5              55                      21                    17
6              23                      40                    37
7              66                      12                    52
8               2                       7                    57
9              30                      82                    62


- Las primeras 5 filas del DataFrame

In [21]:
df[0:5]

Data Warehouse  Python in Data Science  Estadistica Aplicada
0              93                      81                    96
1              89                      64                    39
2              87                      97                    12
3              84                      26                    40
4              41                      56                    31

- Las ultimas 5 filas del DataFrame

In [28]:
df[-5:]

Data Warehouse  Python in Data Science  Estadistica Aplicada
5              55                      21                    17
6              23                      40                    37
7              66                      12                    52
8               2                       7                    57
9              30                      82                    62

- El valor en la celda de la fila # 1 de la columna "Data Warehouse"

In [30]:
df["Data Warehouse"][0]

93

- El valor en la celda de la fila # 3 de la columna "Estadistica Aplicada"

In [31]:
df["Estadistica Aplicada"][2]

12

3. Cree una cuarta columna llamada "Promedio", que se rellena con el promedio fila por fila de las otras 3 columnas ("Data Warehouse", "Python in Data Science", y "Estadistica Aplicada"). Debe de usar la funcion de Numpy para calcular el promedio. 

Para completar esta parte, es útil entender los conceptos básicos de NumPy cubiertos en clase y en la seccion anterior.

In [45]:
df["Promedio"]=round(np.mean(df,axis = 1),2)
print(df)

   Data Warehouse  Python in Data Science  Estadistica Aplicada  Promedio
0              93                      81                    96     90.00
1              89                      64                    39     64.00
2              87                      97                    12     65.33
3              84                      26                    40     50.00
4              41                      56                    31     42.67
5              55                      21                    17     31.00
6              23                      40                    37     33.33
7              66                      12                    52     43.33
8               2                       7                    57     22.00
9              30                      82                    62     58.00


### Vectorización

## Ejericio 4 - Vectorización
A continuacion, se le presenta un problema el cual debera resolver de dos formas distintas. La primera es utilizando un for loop, la segunda usando vectorización. Luego debe de comparar comprar el resultado de ambas implementaciones, tanto el valor resultante de la operacion, como el tiempo que toma la ejecucion de cada una.

### Problema:
Dada una secuencia de precios historicos para una acción, y suponiendo que solo se le permite realizar una compra y una venta, ¿cuál es la ganancia máxima que se puede obtener?

Por ejemplo, dados los precios = (20, 18, 14, 17, 20, 21, 13), el beneficio máximo sería 7, de comprar a 14 y vender a 21. Notar que el arreglo es una secuencia, por lo tanto no es factible solo utilizar los valores menores y mayores, ya que el valor mayor debe de estar obligatoriamente en una posicion futura al menor, por eso el mejor precio de compra es 14 y no 13.

Para este ejemplo utilice el siguiente codigo para generar el dataset (secuencia de precios historicos), asegurese de tambien incluir el "random seed" para obtener reproducibilidad.

In [2]:
# Seed para reproducibilidad
import numpy as np
np.random.seed(42)
# Creamos un arreglo que en su mayoria contiene Nans con algunos "puntos de inflexion" (local min/max).
precios = np.full(100, fill_value=np.nan)
precios[[0, 25, 60, -1]] = [80., 30., 75., 50.]

# De manera lineal interpolamos los valores faltantes y agregamos ruido.
x = np.arange(len(precios))
es_valido = ~np.isnan(precios)
precios = np.interp(x=x, xp=x[es_valido], fp=precios[es_valido])
precios += np.random.randn(len(precios)) * 2
precios

array([80.99342831, 77.7234714 , 77.29537708, 77.04605971, 71.53169325,
       69.53172609, 71.15842563, 67.53486946, 63.06105123, 63.08512009,
       59.07316461, 57.06854049, 56.48392454, 50.17343951, 48.55016433,
       48.87542494, 45.97433776, 46.62849467, 42.18395185, 39.1753926 ,
       42.93129754, 37.5484474 , 36.13505641, 31.15050363, 30.91123455,
       30.22184518, 28.98372713, 33.32282461, 32.65586548, 34.55946964,
       35.2251582 , 41.41884208, 38.97300555, 38.17029243, 43.2165184 ,
       40.41545556, 44.56058433, 41.50923118, 44.05791362, 48.39372247,
       50.76264745, 50.91416513, 51.62584629, 52.54064975, 51.47152745,
       54.2745973 , 56.07872246, 60.39995874, 60.25866515, 57.33106255,
       62.79102508, 62.65840687, 63.36044171, 67.22335258, 69.34771333,
       70.43398881, 68.17870781, 70.52443239, 73.09109829, 75.66537597,
       74.04165152, 73.98765641, 71.50527877, 70.68450983, 74.06094908,
       74.50735185, 71.00982591, 72.51988631, 70.59506692, 67.94

#### utilizando un for loop

In [5]:
import time
tic1 = time.process_time()

beneficio_maximo=0
for i in precios:
    maxi2=0
    for x in precios[list(precios).index(i):]:
        if x-i>maxi:
            maxi=x-i
            if maxi>beneficio_maximo:
                beneficio_maximo=maxi
                v1=i
                v2=x
        
        
print("La ganancia máxima es ", round(beneficio_maximo,2),
      " comprando a ", round(v1,2), "y vendiendo a ", round(v2,2))
phyton_time1 = time.process_time() - tic1
print("Con este método el tiempo fue : ",phyton_time1)

La ganancia máxima es  46.68  comprando a  28.98 y vendiendo a  75.67
Con este método el tiempo fue :  0.003642999999999841


#### usando vectorización

In [7]:
import time
tic2 = time.process_time()

beneficio_maximo=0
for i in precios:
    if max(precios[list(precios).index(i):])-i > beneficio_maximo:
        beneficio_maximo = max(precios[list(precios).index(i):])-i
        v1=i
        v2=max(precios[list(precios).index(i):])
        
print("La ganancia máxima es ", round(beneficio_maximo,2),
      " comprando a ", round(v1,2), "y vendiendo a ", round(v2,2))

phyton_time2 = time.process_time() - tic2
print("Con este método el tiempo fue : ",phyton_time2)

La ganancia máxima es  46.68  comprando a  28.98 y vendiendo a  75.67
Con este método el tiempo fue :  0.0044319999999999915
